### ISSUE TITLE
Upgrading the NERACOOS ERDDAP

### ISSUE THREAD

**Issue by rsignell-usgs** [neracoos-open/NFWF#1]
@ebridger, I just tried adding a WMS endpoint from the NERACOOS ERDDAP to TerriaJS, and it barfed.   

I think the problem is that the version of ERDDAP (1.46) has a bug in the WMS implementation.  

Could you upgrade to the latest version of ERDDAP (1.64)?  

This used to be a PITA, but now is super easy with docker:
https://hub.docker.com/r/axiom/docker-erddap/

**Comment by ebridger** [comment]
@rsignell-usgs  I've been meaning to try docker so this looks like a good opportunity, though I know nothing about it.  Hopefully leaning docker is not a PITA.

**Comment by rsignell-usgs** [comment]
@ebridger , you don't have to learn docker unless you want to package things.  If you want to just use it and install containers that already exist, it's the exact opposite of PITA.  :smile_cat:

**Comment by rsignell-usgs** [comment]
@ebridger, I notice that the NERACOOS ERDDAP is still at version 1.46, so doesn't have the "all datasets" that comes with later versions (and would be super useful to have!), like:
http://coastwatch.pfeg.noaa.gov/erddap/tabledap/allDatasets.html

Are you having issues with Docker?   If so, let's get them resolved!

I can't wait to see this working:
http://www.neracoos.org/erddap/tabledap/allDatasets.html

**Comment by ebridger** [comment]
@rsignell-usgs, Yes I did have issues with Docker on OS X. I run ERDDAP and THREDDS on my laptop, mirroring our AWS server. Docker could not access all of the OS X file system. Just in the last few weeks I got on the Docker Beta program which fixed both the OS X and Windows problems with Docker, so now I've got both running on my laptop. We've set up a new AWS server for Docker, Tomcat, etc so hopefully we can go live soon.

**Comment by rsignell-usgs** [comment]
@ebridger, I just checked again, and 
http://www.neracoos.org/erddap/index.html
is still at 1.46.  

v 1.46 is thirteen(!) releases out of date.   Please can you upgrade?  I can help you install with docker.

**Comment by ebridger** [comment]
@rsignell-usgs Once again I ran into issues with Docker on OS X. Docker Beta for OS X made much progress on local file system mounts, but a recent upgrade broke the old work-arounds. https://github.com/docker/for-mac/issues/811  **Now** I'm able to mirror our production setup on my laptop but when transferring those settings to our ASW instance docker run .... axiom/docker-erddap refuses to start, so I could definitely use help. Perhaps we should do it off line or via a phone call?

**Comment by rsignell-usgs** [comment]
@ebridger , okay, well, how about just upgrading the old-fashioned way?
Download the WAR file, restart tomcat....
or is your java and tomcat too old?

**Comment by ebridger** [comment]
@rsignell-usgs @kwilcox. Yes, the existing server is Java and Tomcat 7. But I figured out the issue. This is a  new AWS instance running ubuntu 14.0.4.  (The existing production server is ubuntu 12.01 which does not really support Docker).  It was created with only an 8G / root directory. By default Docker uses /var/lib/docker which tomcat,thredds and erddap (4.629) and some other images filled up.  This is configurable  and have another disk, so hopefully we'll be good to go soon.

**Comment by rsignell-usgs** [comment]
Land ho!

**Comment by rsignell-usgs** [comment]
@ebridger , any news here?

**Comment by rsignell-usgs** [comment]
I just realized that the problem in cell [10] here: 
http://nbviewer.jupyter.org/gist/rsignell-usgs/704904e1cf15f6dcc5f2521caebb36ee
would not have happened if we were using ERDDAP version 1.62 or higher (June, 2015).
 This is when the "valid_range" attribute started being used by ERDDAP.   

Please upgrade !!!!

**Comment by rsignell-usgs** [comment]
@ebridger, looks like this version of ERDDAP does not support the `max(time)` feature we heard about at the DMAC meeting:
http://www.neracoos.org/erddap/tabledap/B01_sbe37_all.csvp?time,temperature&temperature_qc=0&depth=20.0&time%3E=max(time)-7days

**Comment by ebridger** [comment]
http://www.neracoos.org/erddap/index.html has been at version 1.80 since June 2017.

**Comment by rsignell-usgs** [comment]
Ya.  So good.
