### ISSUE TITLE
Get USACE WIS data

### ISSUE THREAD

**Issue by rsignell-usgs** [neracoos-open/NFWF#5]
The USACE has a thredds server at http://chlthredds.erdc.dren.mil/thredds/catalog.html with some datasets we should include here.   Two major collections are the FRF nearshore data, which contain a lot of storm response sensor data, and the WIS study, a numerical model simulation that produces long-term simulated wave time series at a number of stations along the US Coast & Great Lakes. 

We should get the WIS data as it's low hanging fruit.

**Comment by rsignell-usgs** [comment]
This THREDDS catalog:
http://chlthredds.erdc.dren.mil/thredds/catalog/wis/catalog.html
has a bunch of regions, each region has a bunch of stations, and each station has an aggregation NcML, like this:
http://chlthredds.erdc.dren.mil/thredds/catalog/wis/Atlantic/ST41012/catalog.html?dataset=wisDatasetScan/Atlantic/ST41012/ST41012.ncml

They have ncISO enabled, so all we should need to do is crawl this catalog, picking up the ISO records for only datasets that end in `.ncml`.       Easy!

What do you say @kwilcox?

**Comment by kwilcox** [comment]
Added elsewhere and referenced here, closing
